variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python3 -V  # Print out python version for debugging
  - PKG_VERSION=`cat VERSION`
  - EXPECTED_TAG=release/${PKG_VERSION}
  - EXPECTED_WHEEL=montoux_athena-${PKG_VERSION}-py3-none-any.whl

build-whl:
  tags:
    - asdf-ecs
  stage: build
  script:
    - pip3 install --upgrade build
    - python3 -m build
  artifacts:
    paths:
      - dist

build-doc:
  tags:
    - asdf-ecs
  stage: build
  script:
    - pip3 install --upgrade sphinx sphinx_rtd_theme .
    - python3 -m sphinx -b html doc montoux_athena-doc
  artifacts:
    paths:
      - montoux_athena-doc

test:
  tags:
    - asdf-ecs
  stage: test
  dependencies:
    - build-whl
  script:
    - python3 -m pip install tox
    - python3 -m tox --installpkg dist/$EXPECTED_WHEEL

upload-whl:
  tags:
    - asdf-ecs
  stage: deploy
  dependencies:
    - build-whl
  rules:
    - if: $CI_COMMIT_TAG =~ /^release\//
  script:
    - if test $CI_COMMIT_TAG != $EXPECTED_TAG; then echo "tag does not match package version"; false; fi
    - pip install --upgrade twine awscli
    - aws codeartifact login --tool twine --domain montoux --domain-owner 111197162236 --repository pypi --region ap-southeast-2
    - python -m twine upload -r codeartifact dist/$EXPECTED_WHEEL --verbose

pages:
  tags:
    - asdf-ecs
  stage: deploy
  dependencies:
    - build-doc
  rules:
    - if: $CI_COMMIT_TAG =~ /^release\//
  script:
    - if test $CI_COMMIT_TAG != $EXPECTED_TAG; then echo "tag does not match package version"; false; fi
    - rm -rf public
    - cp -r montoux_athena-doc public
  artifacts:
    paths:
      - public
